"""create pickup_point table

Revision ID: 28caf421b6df
Revises: 26371c1749e6
Create Date: 2025-09-23 12:11:30.355304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28caf421b6df'
down_revision: Union[str, Sequence[str], None] = '26371c1749e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pickup_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('pickup_point_id', sa.Integer(), nullable=True))
    op.alter_column('orders', 'address',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.create_foreign_key('fk_orders_pickup_point_id', 'orders', 'pickup_points', ['pickup_point_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_orders_pickup_point_id', 'orders', type_='foreignkey')
    op.alter_column('orders', 'address',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('orders', 'pickup_point_id')
    op.drop_table('pickup_points')
    # ### end Alembic commands ###
